# Generated by Django 3.1.5 on 2021-05-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=60)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
