# Generated by Django 3.1.5 on 2021-05-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210512_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.tag'),
        ),
    ]
